Fix synchting::instance
In puppet-agent 1.9.3 (at least) puppet::instance throws the error

Error: Could not retrieve catalog from remote server: Error 500 on
SERVER: Server Error: Evaluation Error: Error while evaluating
a Resource Statement, Evaluation Error: Error while evaluating
a Resource Statement, Unknown resource type: 'notifty' at
/etc/puppetlabs/code/environments/feature_TLM_4390_mus/modules/syncthing/manifests/instance.pp:154

this error is because, according to
https://docs.puppet.com/puppet/4.9/lang_expressions.html#regex-or-data-type-match
left operand must be a string and it can't be a hash.

So I have changed the if to check if options has the key
globalAnnounceServer (that is was I supposed that previous if wanted to
do)